sudo: required
services:
    - docker

before_install:
    - docker build -t teevee757/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true teevee757/docker-react npm run test -- --coverage

language: generic

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-1-706921246961"
    bucket_path: "docker-react"
    on:
        branch: master