sudo: required
services:
    - docker

before_install:
    - docker build -t teevee757/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true teevee757/docker-react npm run test

language: generic